name: Create Custom Android Emulator

on:
  push:
    branches: [ main ]

env:
  ANDROID_SDK_ROOT: /usr/local/android-sdk
  ANDROID_HOME: /usr/local/android-sdk
  ANDROID_AVD_HOME: ${GITHUB_WORKSPACE}/.android/avd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Android SDK
      uses: eltonlaw/setup-android@v1
      with:
        android-sdk-version: 6200805
        accept-license: yes

    - name: Create custom emulator device
      run: |
        echo "no" | avdmanager create avd \
            --name custom_device \
            --package "system-images;android-29;google_apis;x86" \
            --device "pixel" \
            --sdcard 1024M

    - name: Launch custom emulator device
      run: |
        emulator -avd custom_device -no-audio -no-window &
        adb wait-for-device
        adb shell input keyevent 82
