name: Connect to local machine
on: [push]
env:
  USERNAME: <your_username> 
  PASSWORD: <your_password>
jobs:
  connect_to_local_machine:
    runs-on: ubuntu-latest
    steps:
    - name: Run sshpass commands
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: 34.125.113.85
        user: faraz_aws_acc
        pass: httphttp
        run: |
          ls
