name: Build Android SDK

on:
  push:
    branches:
      - main

env:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
  ANDROID_HOME: /usr/local/android-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk

    - name: Set up environment variables
      run: |
        echo "export ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

    - name: Create Android SDK
      run: |
        sdkmanager --update
        sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"

    - name: Build Android SDK
      run: ./gradlew build
