name: Test on emulator

on: [push]

env:
  ANDROID_HOME: /opt/android-sdk
  JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Install Android SDK and components
      uses: elmundio87/setup-android-sdk@v0.2.0
      with:
        components: build-tools;29.0.3,platform-tools,android-29,emulator

    - name: Create and start emulator
      run: |
        echo "no" | android create avd --force -n test -t android-29 --abi google_apis/x86
        emulator -avd test -no-audio -no-window &

    - name: Wait for emulator to be ready
      run: |
        ./wait_for_emulator.sh
        adb shell input keyevent 82

#     - name: Build and test with Maven
#       run: |
#         ./mvnw clean test
