name: Create Android Emulator

on:
  push:
    branches: [ main ]

env:
  ANDROID_SDK_ROOT: /usr/local/android-sdk

jobs:
  create_emulator:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Android SDK
      uses: actions/setup-android@v1
      with:
        android-sdk-version: 29

    - name: Create AVD
      run: |
        echo y | $ANDROID_SDK_ROOT/tools/bin/sdkmanager "platform-tools"
        echo y | $ANDROID_SDK_ROOT/tools/bin/sdkmanager "platforms;android-29"
        echo y | $ANDROID_SDK_ROOT/tools/bin/sdkmanager "emulator"
        echo y | $ANDROID_SDK_ROOT/tools/bin/sdkmanager "system-images;android-29;google_apis;x86"

        $ANDROID_SDK_ROOT/tools/bin/avdmanager create avd --name custom_emulator --package 'system-images;android-29;google_apis;x86' --device 'Nexus 5'

    - name: Start Emulator
      run: |
        $ANDROID_SDK_ROOT/emulator/emulator -avd custom_emulator -no-snapshot-load &
        
