name: Connect to local machine
on: [push]
jobs:
  connect_to_local_machine:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: 34.125.113.85
        port:  22
        user: faraz_aws_acc
        command:  echo 'Hello world'
