name: Android CI

on:
  push:
    branches:
      - main

env:
  ANDROID_SDK_ROOT: /usr/local/android-sdk
  ANDROID_HOME: /usr/local/android-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#     - name: Set up JDK
#       uses: actions/setup-java@v1
#       with:
#         java-version: 11

#     - name: Set up Android SDK
#       uses: actions/setup-android@v2
#       with:
#         components: build-tools,platform-tools,android-30

#     - name: Build with Maven
#       run: ./mvnw clean test
