name: Install Android Emulator

on: push

env:
  ANDROID_SDK_TOOLS: "6846975_latest"
  ANDROID_HOME: ${{ env.HOME }}/android-sdk

jobs:
  install_emulator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Set up Android SDK
      uses: actions/setup-android@v1
      with:
        android-sdk-tools: ${{ env.ANDROID_SDK_TOOLS }}

    - name: Install Android Emulator
      run: sdkmanager "emulator" "system-images;android-30;google_apis;x86_64"

    - name: Create AVD
      run: |
        echo no | avdmanager create avd --force --name testAVD --package "system-images;android-30;google_apis;x86_64" --device "pixel"
